// <auto-generated />
namespace adminlte.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class EditDatabasenew : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EditDatabasenew));
        
        string IMigrationMetadata.Id
        {
            get { return "202106281143501_EditDatabasenew"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
