// <auto-generated />
namespace adminlte.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class passengernumber : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(passengernumber));
        
        string IMigrationMetadata.Id
        {
            get { return "202106291013402_passengernumber"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
