// <auto-generated />
namespace adminlte.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ManagePuplicDriver : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ManagePuplicDriver));
        
        string IMigrationMetadata.Id
        {
            get { return "202105220733555_ManagePuplicDriver"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
